original_speed = 0;  // Default movement speed
speed = original_speed;  // Current speed
freeze_timer = 0;  // Freeze timer (e.g., 5 seconds)
freeze_timer_initialized = false; 
frozen = false;  // Is the NPC frozen?
escape_mode = false;  // Is the NPC escaping?
escape_target_x = 0;  // Target X position for escaping
escape_target_y = 0;  // Target Y position for escaping
escape_speed = 2;  // Speed of the NPC when escaping
image_xscale = 0.2;
image_yscale = 0.2; 